### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by lilwayne-horegu** [Aklilu-Mandefro/Personal-Blog#2]
Hello dear Aklilu, I forked and cloned this repository. But, when I try to run it from my browser, nothing displayed. Please help me fix this issue.

Thanks,

**Comment by Aklilu-Mandefro** [comment]
Hey Lilwayne, 
Once you cloned the repository, you have to create a mysql database by a name 'blog_admin_db' from the 'phpMyAdmin' of your server. Then, import the SQL file inside the **databasefile** direcotry into your database you have created so far. Finally, open your browser and access your root folder.

That's it.

Don't hesitate to reach out to me for any further issues.

Cheers!
